<?php
/**
 * @var $block Boxofhope\ReturnLabelPlugin\Block\Admin\Order\View\View
 */

?>

<div class="admin__page-section-title" style="display: none">
    <span class="title"><?php echo $block->showBohDeliveryInfo()?></span>
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
        <tr class="headings">
            <th class=""><span>Product</span></th>
            <th class=""><span>Item Status</span></th>
        </tr>
        </thead>
        <tbody class="two">
        <tr>
            <td>
            </td>
        </tr>
        </tbody>
    </table>
</div>
